### ISSUE TITLE
Tasks for Isabella's onboarding (Octopus).

### ISSUE THREAD

**Issue by scoiatael** [opendesigndev/octopus-specs#20]
In GitLab by @nikitamironov on Feb 3, 2020, 17:33

# Bigger ones
These tasks will take 4-8 weeks to execute.  
### Octopus 3 changes.
Depending on complexity of change it will take different amount of time. It's categorized as bigger task because even for little change we will have to update all the converters, tests, schema and communitcate changes across all teams.
### Writers.
Also bigger task because we need to analyze the file structure of resulting file + Octopus + possible caveats when converting.
### JS Sketch parser
JS implementation of Go Sketch parser.
### Exportables
Research and add into Octopus information about what user marked as exportable. Not that big, but it requires to change all converters where this feature is available.

# Smaller ones
* [ ] XD Uppercase https://gitlab.avcd.cz/backend/backend/issues/1499
* [x] Figma text ranges bug https://gitlab.avcd.cz/backend/backend/issues/1888
* [ ] Remove constructor.name https://gitlab.avcd.cz/avocode/octopus-symbol-expander/issues/30
* [x] Empty `value` on text layers https://gitlab.avcd.cz/avocode/avocode/issues/6840
* [ ] Protomerger issue (I guess, we need to investigate) https://gitlab.avcd.cz/backend/octopus-protomerger/issues/3
* [ ] Figma text transform https://gitlab.avcd.cz/backend/octopus-figma/issues/19
* [x] Mask/opacity bug https://gitlab.avcd.cz/backend/backend/issues/1596
* [ ] Figma design version info https://gitlab.avcd.cz/backend/figma-parser/issues/12
* [ ] Something weird https://gitlab.avcd.cz/avocode/octopus-symbol-expander/issues/29
* [x] Letterspacing in xd https://gitlab.avcd.cz/backend/backend/issues/1278
  
Few more tasks:
* [ ] Rectangle corner radius incorrectly limited https://gitlab.avcd.cz/avocode/octopus-xd/issues/34
* [ ] Add `blendMode` prop https://gitlab.avcd.cz/avocode/octopus-xd/issues/33

I've filtered issues that are quite easy to start work with, although she will still need some kind of consultation.
