### ISSUE TITLE
Octopus Roadmap

### ISSUE THREAD

**Issue by scoiatael** [opendesigndev/octopus-specs#22]
In GitLab by @nikitamironov on Feb 18, 2020, 01:40

- [ ] **Smart Layout documentation**
- [ ] **Documentus output**
  - [x] in node-sketch-parser first
  - [ ] create batch workers for other formats

- [ ] **Octopus 3 implementation**  
  - [Artboard changes](https://gitlab.avcd.cz/backend/octopus/issues/21)
  - [Shape descriptor changes](https://gitlab.avcd.cz/backend/octopus/issues/16)
    - :heavy_plus_sign: Improved performance of octopus converter as it won't need to normalize nested bool ops
  - [Compression technique](https://gitlab.avcd.cz/backend/octopus/issues/19)

- [x] **Exportables info in octopus**  
  -  @isabellaskorepova did a first version of support, ready to review

- [ ] 

- [x] **Use symbols from earlier versions of design** - versioning
  - backend/backend#1917
  - :heavy_plus_sign: Speed up upload of new versions as we wouldn't need to bundle all the used symbols that are unchanged
  - :heavy_plus_sign: Less complexity in Avocode sketch app&plugin
- [ ] **XD Writer**  
  - There still isn't complex research about xd writer, but based on information I know I'll guess needed time as 2-4 weeks for first implementation, few more weeks for writing tests, fixing bugs and adding some edge cases. I guess biggest challenge will be geometry, rest of things are quite clear.
  - :heavy_plus_sign: Needed to be able to download cloud XD documents synced by the new XD Plugin
  - :heavy_plus_sign: Would allow converting of other formats to XD

- [ ] **Sketch parser**  
  - Sketch-parser doesn't do much of business logic, it means sketch parser in JS will not be that big deal. Also, 2-4 weeks, more accurate time will be known after discussion with @janroztocil and understanding the most complex parts of it - backend/backend#1542. I think this task is last by priority in bigger tasks queue since we already have working solution (parser in Go).
  - :heavy_plus_sign: Ability to parse sketch files in browser
  - :heavy_minus_sign: We already have a working backend and native solution

- [x] **Sketch writer**  
  - It will be much easier to implement than xd writer since Octopus data are more similar to Sketch than xd. No matrices, more simple geometry. But still, I guess it will take 2-4 weeks for first version and some time for tests and polishing.
  - :heavy_plus_sign: Could support more input formats than just Photoshop
  - :heavy_plus_sign: Could work in browser
