### ISSUE TITLE
[meta] Octopus plans - early 2021

### ISSUE THREAD

**Issue by scoiatael** [opendesigndev/octopus-specs#35]
In GitLab by @janroztocil on Dec 15, 2020, 14:57

## General Octopus
- [x] [**high-prio**] finish XD shapes fix @nikitamironov 
- [x] Octopus format OpenAPI specification (docs for users, types for us) @janroztocil
- [x] support Figma Component Variants in octopus-figma
- [ ] support XD Component States in octopus-xd
- [ ] [*low-prio*] Figma canvas level transformation https://gitlab.avcd.cz/backend/backend/-/issues/2352
- [ ] [*low-prio*][pending MR] code review https://gitlab.avcd.cz/backend/backend/-/issues/2146 @nikitamironov 
- [ ] [*low-prio*][pending MR] code review https://gitlab.avcd.cz/backend/backend/-/issues/2147 @nikitamironov 
- [ ] empty bounds: 1) `path.bounds` in Photoshop [octopus](https://cloudfront.designs.avcd.cz/2020/8/d347176f4f73493da505d66e557fb00e/octopus_2.2.9.1018873.json) and `layer.bounds` in XD text layers (auto-* frame) [octopus](https://cloudfront.designs.avcd.cz/2020/12/8fa5a1cf22c549c5b2d327a8ff7add85/octopus_2.2.70.1072891.json)
- [ ] [expander] `null` where numbers are expected (`bounds`, `coords`), it's OK in plain octopus, expander breaks it, layer has `0` height though https://gitlab.avcd.cz/avocode/octopus-symbol-expander/-/issues/36
- [ ] [*low-prio*] Figma respect no fill on text layer, currently there's always opaque black color fill even if there's no fill in Figma

- [ ] [*long-term*] use TypeScript for all the tools (depends on Octopus format spec)
- [ ] [*low-prio*] NPM publish from Gitlab CI
- [ ] Figma missing rounded corners on nested artboards
- [ ] Figma: respect no color fill on text layers

### Sketch Writer
- [ ] check feasibility of using the code base for other sources than Figma, refactor where needed @nikitamironov 

#### Figma-to-Sketch
- [ ] Update known issue, Most of them should be fixed, finish or at least document the rest: [notion](https://www.notion.so/avocode/Figma-Sketch-conversion-results-84840d03d9ce4196a979d78fad7914bd) @nikitamironov 
- [ ] [phase-2] Convert Figma compontents to Sketch symbols
- [ ] [phase-2] Convert Figma Auto Layout to Sketch Smart Layout

#### XD-to-Sketch
- [ ] Try out the new Sketch writer with XD Octopuses

#### Photoshop-to-Sketch
- [ ] [phase 2] Try out new sketch writer with PS Octopuses, document the issues
- [x] Fix "legacy" (Go) sketch writer @janroztocil

#### AI-to-Sketch
- [ ] try out

### XD Writer
- [ ] Create basic XD file structure (could we reuse some of Sketch Writer and/or XD Writer Plugin code?)
- [ ] [TBD] TypeScript for XD format
- [ ] Figma -> XD
- [ ] Photoshop -> XD
- [ ] [TBD] Sketch -> XD

## Rendering

- [ ] rounded rectangles from XD research, is it octopus or rendering? https://gitlab.avcd.cz/avocode/octopus-xd/-/issues/34 @janroztocil 
- [ ] rendering CLI HOW-TO use for Octopus development @janroztocil 
- [x] transformed shapes in Figma research/fix https://gitlab.avcd.cz/backend/rendering/-/issues/413 @janroztocil
