### ISSUE TITLE
Change root version to schema version and add converter version to meta

### ISSUE THREAD

**Issue by rychlis** [opendesigndev/octopus-specs#63]
- [x] decide on new format
- [x] implement
- [x] also make sure we have schema version changelog up to date
- [x] release 3.0.0 without alpha tag
